services:
    _defaults:
        autoconfigure: true
        public: false

    wordpressimporter:
        class: WordPressImportBundle\Service\Importer
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@contao.framework'
            - '@event_dispatcher'
            - '@logger'
            - '%kernel.project_dir%'

    wordpressimport_command:
        class: WordPressImportBundle\Command\ImportCommand
        arguments: ['@wordpressimporter']

    wordpressimport_cron:
        public: true
        class: WordPressImportBundle\Utils\Cron
        arguments: ['@wordpressimporter', '@logger', '@contao.framework']

    WordPressImportBundle\EventListener\ApiResponseBodyListener:
        autowire: true